# Generated by Django 4.2.7 on 2025-01-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_choice',
            field=models.CharField(blank=True, choices=[('bca', 'ATM BCA'), ('bri', 'ATM BRI'), ('mandiri', 'ATM Mandiri'), ('bni', 'ATM BNI')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ewallet_choice',
            field=models.CharField(blank=True, choices=[('dana', 'Dana'), ('gopay', 'Gopay'), ('ovo', 'OVO'), ('linkaja', 'LinkAja')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('digital_wallet', 'Dompet Digital')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
